# Generated by Django 5.1 on 2024-09-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('votes', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('genres', models.CharField(max_length=255)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('languages', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=512)),
                ('banner_path', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
    ]
