# Generated by Django 5.1 on 2024-09-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_role', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=200)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(max_length=255)),
                ('crew_role', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.movie')),
            ],
        ),
    ]
