# Generated by Django 5.1 on 2024-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_movie_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=100)),
                ('age_limit', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=200)),
                ('banner_path', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
