# Generated by Django 5.1 on 2024-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_event_theatre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=200)),
                ('banner_path', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
