# Generated by Django 5.1 on 2024-09-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('show_date', models.CharField(max_length=20)),
                ('show_timing', models.CharField(max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.theatre')),
            ],
        ),
    ]
