# Generated by Django 5.1 on 2024-09-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='anchor_link',
            field=models.TextField(default='html/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
