# Generated by Django 5.1 on 2024-09-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_movie_anchor_link_movie_like_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='anchor_link',
        ),
    ]
