# Generated by Django 5.1 on 2024-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_movie_anchor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='like_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
