# Generated by Django 5.1 on 2024-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_event_like_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='votes',
            field=models.CharField(default='0k', max_length=20),
        ),
    ]
