# Generated by Django 5.1 on 2024-09-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sport_like_percentage_sport_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seats_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.TextField()),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.showtime')),
            ],
        ),
    ]
