# Generated by Django 5.1 on 2024-09-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_seat_seats_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='show_id',
            new_name='show',
        ),
    ]
